import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import SideNav from "./ui/sidenav/sidenav";
import { auth } from "@/auth";
import { EdgeStoreProvider } from "./lib/edgestroe";
import SessionProvider from './session-provider';
import RightSideBar from "./ui/right-sidebar/right-sidebar";

const robot_mono = Roboto_Mono({
  subsets: ['latin'],
  variable: '--font-roboto-mono',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body className={robot_mono.className}>
        <EdgeStoreProvider>
          <SessionProvider session={session}>
            <div className="flex px-1 sm:px-6 h-fit bg-white justify-center">
              {session?.user && <SideNav />}
              <div className="ml-1 border-x border-gray-200 max-w-[580px] w-full sm:w-4/5 md:w-3/3">
                {children}
              </div>
              {session?.user && <RightSideBar />}
            </div>
          </SessionProvider>
        </EdgeStoreProvider>
      </body>
    </html>
  );
}
